version: '3.5'

volumes:
  prometheus_data:
  grafana_data:

services:

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=4w'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=127.0.0.1:9090'
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    restart: always
    ports:
      - 127.0.0.1:9090:9090
    network_mode: host

  grafana:
    image: grafana/grafana:6.7.0
    env_file: grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    ports:
      - 0.0.0.0:3000:3000
    network_mode: host
